package com.lsmp.model;
// Generated 20 mars 2015 12:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alerte generated by hbm2java
 */
@Entity
@Table(name="alerte"
    ,catalog="lsmp"
)
public class Alerte  implements java.io.Serializable {


     private Integer idAlerte;
     private String objetAlerte;
     private String descriptionAlerte;
     private Date dateAlerte;
     private String nomAlerte;
     private String emailAlerte;
     private String telAlerte;

    public Alerte() {
    }

    public Alerte(String objetAlerte, String descriptionAlerte, Date dateAlerte, String nomAlerte, String emailAlerte, String telAlerte) {
       this.objetAlerte = objetAlerte;
       this.descriptionAlerte = descriptionAlerte;
       this.dateAlerte = dateAlerte;
       this.nomAlerte = nomAlerte;
       this.emailAlerte = emailAlerte;
       this.telAlerte = telAlerte;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_alerte", unique=true, nullable=false)
    public Integer getIdAlerte() {
        return this.idAlerte;
    }
    
    public void setIdAlerte(Integer idAlerte) {
        this.idAlerte = idAlerte;
    }

    
    @Column(name="objet_alerte", nullable=false)
    public String getObjetAlerte() {
        return this.objetAlerte;
    }
    
    public void setObjetAlerte(String objetAlerte) {
        this.objetAlerte = objetAlerte;
    }

    
    @Column(name="description_alerte", nullable=false, length=65535)
    public String getDescriptionAlerte() {
        return this.descriptionAlerte;
    }
    
    public void setDescriptionAlerte(String descriptionAlerte) {
        this.descriptionAlerte = descriptionAlerte;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_alerte", nullable=false, length=19)
    public Date getDateAlerte() {
        return this.dateAlerte;
    }
    
    public void setDateAlerte(Date dateAlerte) {
        this.dateAlerte = dateAlerte;
    }

    
    @Column(name="nom_alerte", nullable=false, length=50)
    public String getNomAlerte() {
        return this.nomAlerte;
    }
    
    public void setNomAlerte(String nomAlerte) {
        this.nomAlerte = nomAlerte;
    }

    
    @Column(name="email_alerte", nullable=false, length=100)
    public String getEmailAlerte() {
        return this.emailAlerte;
    }
    
    public void setEmailAlerte(String emailAlerte) {
        this.emailAlerte = emailAlerte;
    }

    
    @Column(name="tel_alerte", nullable=false, length=10)
    public String getTelAlerte() {
        return this.telAlerte;
    }
    
    public void setTelAlerte(String telAlerte) {
        this.telAlerte = telAlerte;
    }




}


