package com.lsmp.model;
// Generated 20 mars 2015 12:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Intervention generated by hbm2java
 */
@Entity
@Table(name="intervention"
    ,catalog="lsmp"
)
public class Intervention  implements java.io.Serializable {


     private Integer idIntervention;
     private Mission mission;
     private Utilisateur utilisateur;
     private String rapportIntervention;
     private String constatationIntervention;
     private Date dateIntervention;
     private Date dateModificationIntervention;

    public Intervention() {
    }

    public Intervention(Mission mission, Utilisateur utilisateur, String rapportIntervention, String constatationIntervention, Date dateIntervention, Date dateModificationIntervention) {
       this.mission = mission;
       this.utilisateur = utilisateur;
       this.rapportIntervention = rapportIntervention;
       this.constatationIntervention = constatationIntervention;
       this.dateIntervention = dateIntervention;
       this.dateModificationIntervention = dateModificationIntervention;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_intervention", unique=true, nullable=false)
    public Integer getIdIntervention() {
        return this.idIntervention;
    }
    
    public void setIdIntervention(Integer idIntervention) {
        this.idIntervention = idIntervention;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intervention_mission", nullable=false)
    public Mission getMission() {
        return this.mission;
    }
    
    public void setMission(Mission mission) {
        this.mission = mission;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intervenant_id", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="rapport_intervention", nullable=false, length=65535)
    public String getRapportIntervention() {
        return this.rapportIntervention;
    }
    
    public void setRapportIntervention(String rapportIntervention) {
        this.rapportIntervention = rapportIntervention;
    }

    
    @Column(name="constatation_intervention", nullable=false, length=65535)
    public String getConstatationIntervention() {
        return this.constatationIntervention;
    }
    
    public void setConstatationIntervention(String constatationIntervention) {
        this.constatationIntervention = constatationIntervention;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_intervention", nullable=false, length=19)
    public Date getDateIntervention() {
        return this.dateIntervention;
    }
    
    public void setDateIntervention(Date dateIntervention) {
        this.dateIntervention = dateIntervention;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modification_intervention", nullable=false, length=19)
    public Date getDateModificationIntervention() {
        return this.dateModificationIntervention;
    }
    
    public void setDateModificationIntervention(Date dateModificationIntervention) {
        this.dateModificationIntervention = dateModificationIntervention;
    }




}


