package com.lsmp.model;
// Generated 20 mars 2015 12:07:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name="mission"
    ,catalog="lsmp"
)
public class Mission  implements java.io.Serializable {


     private Integer idMission;
     private TypeMission typeMission;
     private Utilisateur utilisateurByDemandeurId;
     private Utilisateur utilisateurByIntervenantId;
     private String libelleMission;
     private String descriptionMission;
     private String statutMission;
     private String prioriteMission;
     private Date deadlineMission;
     private Date dateCreationMission;
     private Date dateModificationMission;
     private Set<Infrastructure> infrastructures = new HashSet<Infrastructure>(0);
     private Set<Intervention> interventions = new HashSet<Intervention>(0);

    public Mission() {
    }

	
    public Mission(TypeMission typeMission, Utilisateur utilisateurByDemandeurId, Utilisateur utilisateurByIntervenantId, String libelleMission, String descriptionMission, String statutMission, String prioriteMission, Date deadlineMission, Date dateCreationMission, Date dateModificationMission) {
        this.typeMission = typeMission;
        this.utilisateurByDemandeurId = utilisateurByDemandeurId;
        this.utilisateurByIntervenantId = utilisateurByIntervenantId;
        this.libelleMission = libelleMission;
        this.descriptionMission = descriptionMission;
        this.statutMission = statutMission;
        this.prioriteMission = prioriteMission;
        this.deadlineMission = deadlineMission;
        this.dateCreationMission = dateCreationMission;
        this.dateModificationMission = dateModificationMission;
    }
    public Mission(TypeMission typeMission, Utilisateur utilisateurByDemandeurId, Utilisateur utilisateurByIntervenantId, String libelleMission, String descriptionMission, String statutMission, String prioriteMission, Date deadlineMission, Date dateCreationMission, Date dateModificationMission, Set<Infrastructure> infrastructures, Set<Intervention> interventions) {
       this.typeMission = typeMission;
       this.utilisateurByDemandeurId = utilisateurByDemandeurId;
       this.utilisateurByIntervenantId = utilisateurByIntervenantId;
       this.libelleMission = libelleMission;
       this.descriptionMission = descriptionMission;
       this.statutMission = statutMission;
       this.prioriteMission = prioriteMission;
       this.deadlineMission = deadlineMission;
       this.dateCreationMission = dateCreationMission;
       this.dateModificationMission = dateModificationMission;
       this.infrastructures = infrastructures;
       this.interventions = interventions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_mission", unique=true, nullable=false)
    public Integer getIdMission() {
        return this.idMission;
    }
    
    public void setIdMission(Integer idMission) {
        this.idMission = idMission;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission_type", nullable=false)
    public TypeMission getTypeMission() {
        return this.typeMission;
    }
    
    public void setTypeMission(TypeMission typeMission) {
        this.typeMission = typeMission;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="demandeur_id", nullable=false)
    public Utilisateur getUtilisateurByDemandeurId() {
        return this.utilisateurByDemandeurId;
    }
    
    public void setUtilisateurByDemandeurId(Utilisateur utilisateurByDemandeurId) {
        this.utilisateurByDemandeurId = utilisateurByDemandeurId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intervenant_id", nullable=false)
    public Utilisateur getUtilisateurByIntervenantId() {
        return this.utilisateurByIntervenantId;
    }
    
    public void setUtilisateurByIntervenantId(Utilisateur utilisateurByIntervenantId) {
        this.utilisateurByIntervenantId = utilisateurByIntervenantId;
    }

    
    @Column(name="libelle_mission", nullable=false, length=50)
    public String getLibelleMission() {
        return this.libelleMission;
    }
    
    public void setLibelleMission(String libelleMission) {
        this.libelleMission = libelleMission;
    }

    
    @Column(name="description_mission", nullable=false)
    public String getDescriptionMission() {
        return this.descriptionMission;
    }
    
    public void setDescriptionMission(String descriptionMission) {
        this.descriptionMission = descriptionMission;
    }

    
    @Column(name="statut_mission", nullable=false)
    public String getStatutMission() {
        return this.statutMission;
    }
    
    public void setStatutMission(String statutMission) {
        this.statutMission = statutMission;
    }

    
    @Column(name="priorite_mission", nullable=false)
    public String getPrioriteMission() {
        return this.prioriteMission;
    }
    
    public void setPrioriteMission(String prioriteMission) {
        this.prioriteMission = prioriteMission;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deadline_mission", nullable=false, length=19)
    public Date getDeadlineMission() {
        return this.deadlineMission;
    }
    
    public void setDeadlineMission(Date deadlineMission) {
        this.deadlineMission = deadlineMission;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_creation_mission", nullable=false, length=19)
    public Date getDateCreationMission() {
        return this.dateCreationMission;
    }
    
    public void setDateCreationMission(Date dateCreationMission) {
        this.dateCreationMission = dateCreationMission;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modification_mission", nullable=false, length=19)
    public Date getDateModificationMission() {
        return this.dateModificationMission;
    }
    
    public void setDateModificationMission(Date dateModificationMission) {
        this.dateModificationMission = dateModificationMission;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="infrastructure_mission", catalog="lsmp", joinColumns = { 
        @JoinColumn(name="mission_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="infrastructure_id", nullable=false, updatable=false) })
    public Set<Infrastructure> getInfrastructures() {
        return this.infrastructures;
    }
    
    public void setInfrastructures(Set<Infrastructure> infrastructures) {
        this.infrastructures = infrastructures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mission")
    public Set<Intervention> getInterventions() {
        return this.interventions;
    }
    
    public void setInterventions(Set<Intervention> interventions) {
        this.interventions = interventions;
    }




}


