package com.lsmp.model;
// Generated 20 mars 2015 12:07:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeMission generated by hbm2java
 */
@Entity
@Table(name="type_mission"
    ,catalog="lsmp"
)
public class TypeMission  implements java.io.Serializable {


     private Integer idTypeMission;
     private String libelle;
     private Set<Mission> missions = new HashSet<Mission>(0);

    public TypeMission() {
    }

	
    public TypeMission(String libelle) {
        this.libelle = libelle;
    }
    public TypeMission(String libelle, Set<Mission> missions) {
       this.libelle = libelle;
       this.missions = missions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_type_mission", unique=true, nullable=false)
    public Integer getIdTypeMission() {
        return this.idTypeMission;
    }
    
    public void setIdTypeMission(Integer idTypeMission) {
        this.idTypeMission = idTypeMission;
    }

    
    @Column(name="libelle", nullable=false, length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeMission")
    public Set<Mission> getMissions() {
        return this.missions;
    }
    
    public void setMissions(Set<Mission> missions) {
        this.missions = missions;
    }




}


