package com.lsmp.model;
// Generated 20 mars 2015 12:07:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,catalog="lsmp"
)
public class Utilisateur  implements java.io.Serializable {


     private Integer idUtilisateur;
     private TypeUtilisateur typeUtilisateur;
     private String identifiantUtilisateur;
     private String mdpUtilisateur;
     private String mailUtilisateur;
     private String organisationUtilisateur;
     private String nomUtilisateur;
     private String prenomUtilisateur;
     private Set<Mission> missionsForDemandeurId = new HashSet<Mission>(0);
     private Set<Mission> missionsForIntervenantId = new HashSet<Mission>(0);
     private Set<Intervention> interventions = new HashSet<Intervention>(0);

    public Utilisateur() {
    }

	
    public Utilisateur(TypeUtilisateur typeUtilisateur, String identifiantUtilisateur, String mdpUtilisateur, String mailUtilisateur, String organisationUtilisateur, String nomUtilisateur, String prenomUtilisateur) {
        this.typeUtilisateur = typeUtilisateur;
        this.identifiantUtilisateur = identifiantUtilisateur;
        this.mdpUtilisateur = mdpUtilisateur;
        this.mailUtilisateur = mailUtilisateur;
        this.organisationUtilisateur = organisationUtilisateur;
        this.nomUtilisateur = nomUtilisateur;
        this.prenomUtilisateur = prenomUtilisateur;
    }
    public Utilisateur(TypeUtilisateur typeUtilisateur, String identifiantUtilisateur, String mdpUtilisateur, String mailUtilisateur, String organisationUtilisateur, String nomUtilisateur, String prenomUtilisateur, Set<Mission> missionsForDemandeurId, Set<Mission> missionsForIntervenantId, Set<Intervention> interventions) {
       this.typeUtilisateur = typeUtilisateur;
       this.identifiantUtilisateur = identifiantUtilisateur;
       this.mdpUtilisateur = mdpUtilisateur;
       this.mailUtilisateur = mailUtilisateur;
       this.organisationUtilisateur = organisationUtilisateur;
       this.nomUtilisateur = nomUtilisateur;
       this.prenomUtilisateur = prenomUtilisateur;
       this.missionsForDemandeurId = missionsForDemandeurId;
       this.missionsForIntervenantId = missionsForIntervenantId;
       this.interventions = interventions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_utilisateur", unique=true, nullable=false)
    public Integer getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(Integer idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="utilisateur_type", nullable=false)
    public TypeUtilisateur getTypeUtilisateur() {
        return this.typeUtilisateur;
    }
    
    public void setTypeUtilisateur(TypeUtilisateur typeUtilisateur) {
        this.typeUtilisateur = typeUtilisateur;
    }

    
    @Column(name="identifiant_utilisateur", nullable=false, length=20)
    public String getIdentifiantUtilisateur() {
        return this.identifiantUtilisateur;
    }
    
    public void setIdentifiantUtilisateur(String identifiantUtilisateur) {
        this.identifiantUtilisateur = identifiantUtilisateur;
    }

    
    @Column(name="mdp_utilisateur", nullable=false)
    public String getMdpUtilisateur() {
        return this.mdpUtilisateur;
    }
    
    public void setMdpUtilisateur(String mdpUtilisateur) {
        this.mdpUtilisateur = mdpUtilisateur;
    }

    
    @Column(name="mail_utilisateur", nullable=false, length=100)
    public String getMailUtilisateur() {
        return this.mailUtilisateur;
    }
    
    public void setMailUtilisateur(String mailUtilisateur) {
        this.mailUtilisateur = mailUtilisateur;
    }

    
    @Column(name="organisation_utilisateur", nullable=false, length=50)
    public String getOrganisationUtilisateur() {
        return this.organisationUtilisateur;
    }
    
    public void setOrganisationUtilisateur(String organisationUtilisateur) {
        this.organisationUtilisateur = organisationUtilisateur;
    }

    
    @Column(name="nom_utilisateur", nullable=false, length=50)
    public String getNomUtilisateur() {
        return this.nomUtilisateur;
    }
    
    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }

    
    @Column(name="prenom_utilisateur", nullable=false, length=50)
    public String getPrenomUtilisateur() {
        return this.prenomUtilisateur;
    }
    
    public void setPrenomUtilisateur(String prenomUtilisateur) {
        this.prenomUtilisateur = prenomUtilisateur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateurByDemandeurId")
    public Set<Mission> getMissionsForDemandeurId() {
        return this.missionsForDemandeurId;
    }
    
    public void setMissionsForDemandeurId(Set<Mission> missionsForDemandeurId) {
        this.missionsForDemandeurId = missionsForDemandeurId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateurByIntervenantId")
    public Set<Mission> getMissionsForIntervenantId() {
        return this.missionsForIntervenantId;
    }
    
    public void setMissionsForIntervenantId(Set<Mission> missionsForIntervenantId) {
        this.missionsForIntervenantId = missionsForIntervenantId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set<Intervention> getInterventions() {
        return this.interventions;
    }
    
    public void setInterventions(Set<Intervention> interventions) {
        this.interventions = interventions;
    }




}


